### ISSUE TITLE
Javascript error when the mouse is move fast in a random directions

### ISSUE THREAD

**Issue by estronque** [vaadin/vaadin-menu-bar-flow#58] opened 2019-10-07 08:29 UTC
See the attach file.

https://user-images.githubusercontent.com/5946847/66296133-2e1c2380-e8ed-11e9-9260-60b4a02291b9.gif

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at HTMLElement.__alignOverlayPosition (vaadin-menu-bar-interactions-mixin.js?71e0:197)
    at HTMLElement.eval (vaadin-overlay.js?f3eb:548)
    at callMethod (render-status.js?40cd:53)
    at runQueue (render-status.js?40cd:44)
    at eval (render-status.js?40cd:31)

**Comment by web-padawan** [comment] 2020-07-24 07:53
Closing as duplicate of https://github.com/vaadin/vaadin-menu-bar/issues/85 which was fixed by https://github.com/vaadin/vaadin-menu-bar/commit/0dd73804336e600c13856759fb825c7a27ae0e5d

**Closed by web-padawan** 2020-07-24 07:53 UTC
