### ISSUE TITLE
Classnames in "root"-MenuItems are ignored

### ISSUE THREAD

**Issue by AB-xdev** [vaadin/vaadin-menu-bar-flow#96] opened 2020-07-14 08:29 UTC
### Current situation
The following code produces this:
![grafik](https://user-images.githubusercontent.com/45384811/87402150-6f97d880-c5bb-11ea-8dcb-7c0f10f4e4ab.png)

```JAVA
import com.vaadin.flow.component.dependency.CssImport;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.menubar.MenuBar;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("test")
@CssImport("./test.css")
public class TestView extends VerticalLayout
{
	public TestView()
	{
		final MenuBar menuBar = new MenuBar();
				
		menuBar.addItem(this.createLabelWithCss())
			.getSubMenu()
			.addItem(this.createLabelWithCss());
		
		this.add(this.createLabelWithCss(), menuBar);
	}
	
	private Label createLabelWithCss()
	{
		final Label lbl = new Label("Test");
		lbl.addClassName("testcolor");
		
		return lbl;
	}
}
```

test.css
```css
.testcolor {
	color: red;
}
```

#### Expected
The text in the "root"-MenuItem is also red.

### Possible cause
It looks like the root item is inside a shadow-root and through that can't find the styles which are located outside:
![grafik](https://user-images.githubusercontent.com/45384811/87402646-2ac07180-c5bc-11ea-93fa-a13a979fb508.png)

In the overlay it's not inside a shadow-root and therefore working correctly:
![grafik](https://user-images.githubusercontent.com/45384811/87402814-5f342d80-c5bc-11ea-9ea1-83043dc8eed8.png)

### Environment
* Vaadin 14.2
* OpenJDK 11
* Wildfly 19
* Win 10

**Comment by web-padawan** [comment] 2020-07-14 11:47
Thanks for the issue. If you want to styles to apply to root items, please use the following:

```
@CssImport(value = "./test.css", themeFor = "vaadin-menu-bar")
```

This is by design: we use Shadow DOM to prevent arbitrary styles from leaking into components.
The dropdown items are working differently because of how the menu overlay is teleported to `body` when opened.

See also the [documentation](https://vaadin.com/docs/v14/themes/sharing-style-sheets.html#component-style-scope) regarding component style scope.

Closing this as working as intended.

**Closed by web-padawan** 2020-07-14 11:47 UTC
