### ISSUE TITLE
Provide method for styling vaadin-menu-bar-button

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-menu-bar-flow#74] opened 2020-02-27 17:09 UTC
MenuBar::addItem returns a MenuItem (vaadin-context-menu-item), and it's not possible to style the containing vaadin-menu-bar-button associated to it.

```
MenuBar menuBar = new MenuBar();
menuBar.setClassName("mainmenu");
menuBar.addItem("A").getElement().getClassList().add("current");
menuBar.addItem("B");
menuBar.addItem("C");
```

Vaadin version: 14.1.17

**Comment by web-padawan** [comment] 2020-07-24 07:50
Closing as working as intended. The buttons can be styled using `@CssImport`:

```
@CssImport(value = "./my-menu-button.css", themeFor = "vaadin-menu-bar-button")
```

Check [Lumo styles](https://github.com/vaadin/vaadin-menu-bar/blob/master/theme/lumo/vaadin-menu-bar-button-styles.html) as an example. See also https://github.com/vaadin/vaadin-menu-bar-flow/issues/96#issuecomment-658134813

**Closed by web-padawan** 2020-07-24 07:50 UTC
